server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
# Specify the path of the OpenAPI documentation
springdoc:
  swagger-ui:
    path: "/swagger-ui"
    enabled: true

  graphql:
    graphiql:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled:
