# Specify the path of the OpenAPI documentation
springdoc:
  swagger-ui:
    path: "/swagger-ui"
    enabled: true
spring:
  graphql:
    graphiql:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled:
